name: Deploy All Lambda Functions to AWS

on:
  push:
    branches:
      - 'main'
    paths:
      - 'lambda/**/lambda_function.py'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # --- Deploy get_all_inventory_items ---
      - name: Zip get_all_inventory_items
        run: zip -r function.zip . -x "*.git*"
        working-directory: ./lambda/get_all_inventory_items

      - name: Deploy get_all_inventory_items
        run: |
          aws lambda update-function-code \
            --function-name get_all_inventory_items \
            --zip-file fileb://function.zip \
            --publish
        working-directory: ./lambda/get_all_inventory_items

      - name: Cleanup get_all_inventory_items
        run: rm function.zip
        working-directory: ./lambda/get_all_inventory_items

      # --- Deploy get_inventory_item ---
      - name: Zip get_inventory_item
        run: zip -r function.zip . -x "*.git*"
        working-directory: ./lambda/get_inventory_item

      - name: Deploy get_inventory_item
        run: |
          aws lambda update-function-code \
            --function-name get_inventory_item \
            --zip-file fileb://function.zip \
            --publish
        working-directory: ./lambda/get_inventory_item

      - name: Cleanup get_inventory_item
        run: rm function.zip
        working-directory: ./lambda/get_inventory_item

      # --- Deploy add_inventory_item ---
      - name: Install ulid-py for add_inventory_item
        run: pip install ulid-py -t .
        working-directory: ./lambda/add_inventory_item

      - name: Zip add_inventory_item
        run: zip -r function.zip . -x "*.git*"
        working-directory: ./lambda/add_inventory_item

      - name: Deploy add_inventory_item
        run: |
          aws lambda update-function-code \
            --function-name add_inventory_item \
            --zip-file fileb://function.zip \
            --publish
        working-directory: ./lambda/add_inventory_item

      - name: Cleanup add_inventory_item
        run: rm function.zip
        working-directory: ./lambda/add_inventory_item

      # --- Deploy delete_inventory_item ---
      - name: Zip delete_inventory_item
        run: zip -r function.zip . -x "*.git*"
        working-directory: ./lambda/delete_inventory_item

      - name: Deploy delete_inventory_item
        run: |
          aws lambda update-function-code \
            --function-name delete_inventory_item \
            --zip-file fileb://function.zip \
            --publish
        working-directory: ./lambda/delete_inventory_item

      - name: Cleanup delete_inventory_item
        run: rm function.zip
        working-directory: ./lambda/delete_inventory_item

      # --- Deploy get_location_inventory_items ---
      - name: Zip get_location_inventory_items
        run: zip -r function.zip . -x "*.git*"
        working-directory: ./lambda/get_location_inventory_items

      - name: Deploy get_location_inventory_items
        run: |
          aws lambda update-function-code \
            --function-name get_location_inventory_items \
            --zip-file fileb://function.zip \
            --publish
        working-directory: ./lambda/get_location_inventory_items

      - name: Cleanup get_location_inventory_items
        run: rm function.zip
        working-directory: ./lambda/get_location_inventory_items
